#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "[+] Error: Se admite solo un parámetro (archivo de entrada)"
    exit 1
fi

input_file="$1"

if [ ! -r "$input_file" ]; then
    echo "[+] Error: El archivo de entrada no existe o no es legible"
    exit 1
fi

handle_error() {
    echo "[+] Error: $1"
    rm -f "$temp_file"
    exit 1
}

trap 'handle_error "Se produjo un error inesperado."' ERR

temp_file=$(mktemp) || handle_error "No se pudo crear un archivo temporal"

# Extraer información
ports=$(grep -oP '\d{1,5}/open' "$input_file" | awk -F'/' '{print $1}' | xargs | tr ' ' ',')
ip_address=$(grep -oP '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b' "$input_file" | sort -u | head -n 1)

{
    echo -e "\n[*] Extracting information...\n"
    echo -e "\t[*] IP Address: $ip_address"
    echo -e "\t[*] Open ports: $ports\n"
    echo $ports | tr -d '\n' | xclip -sel clip
    echo -e "[*] Ports copied to clipboard\n"
} > "$temp_file"

cat "$temp_file"

rm -f "$temp_file"