#!/usr/bin/bash

if [ $# -ne 1 ]; then
    echo "[+] Error: Se admite solo un parámetro"
    exit 1
fi

directory() {
    directorio="$1"
    echo "[+] Creando directorio..."
    sleep 1
    mkdir -p "$directorio" || { echo "[+] Error al crear el directorio"; exit 1; }
    cd "$directorio" || { echo "[+] Error al cambiar al directorio"; exit 1; }

    echo "[+] Creando subdirectorios de trabajo..."
    sleep 3
    mkdir recognition content exploit script information_target || { echo "[+] Error al crear subdirectorios"; exit 1; }
    echo "[+] Directorios creados correctamente."
}

directory "$1"
